### ISSUE TITLE
Endless loop in cookbook.(*CookbookVersion).resolveDependencies if cookbooks have circular dependencies

### ISSUE THREAD

**Issue by oker1** [ctdk/goiardi#31]
We have two cookbooks depending on each other (I know it's pretty bad), and it makes the memory usage explode as soon as a client tries to use these cookbooks. It starts to allocate memory without end until the process is killed. If I break the dependency cycle it works normally.

We are using these same cookbooks with Opscode Chef Server 11, without problems.

**Comment by ctdk** [comment]
Yeah, the depsolver's always been a little weak. I'm surprised that this case (along with the zero byte file in the other issue) isn't covered in the chef-pedant tests, but here we are. I was planning on fixing the depsolver anyway, so I may as well finally get that out of the way too.

**Comment by ctdk** [comment]
At last, I have the rewritten depsolver in a state where I believe it's suitable for testing again. It's now sending back errors in the format chef-pedant expects, although some of the error messages need further refinement. More importantly here, it's more robust and shouldn't blow up like you had happen anymore. Of course, since the depsolver's a pretty touchy piece of the software, testing is appreciated.

**Comment by oker1** [comment]
Awesome! I'll test it today.

**Comment by oker1** [comment]
I get an error in chef-client:

https://gist.github.com/oker1/6bc2110838d4a1fdd966

I'll try to dig into a bit more.

**Comment by ctdk** [comment]
If you haven't, could you run that with debug on? I have a feeling I know where that's coming from, but if you could try running it with more debug output that'd help narrow it down.

**Comment by ctdk** [comment]
I've been getting back in the goiardi saddle recently, and just duplicated this bug. This should be figured out fairly soon.

**Comment by ctdk** [comment]
Well, that was a stupid error on my part. I pushed a fix for this up on the 0.9.1-dev branch. Urk.

**Comment by ctdk** [comment]
And even better, it looks like the circular dependencies no longer makes the memory usage explode. Huzzah! @oker1, if you see this, I believe this problem is finally fixed for you. Sorry for the delay; I got super busy with vacation and various non-goiardi things, and couldn't work on it for a little while.

**Comment by ctdk** [comment]
The fix for this is now in master, and seems to work well.
