### ISSUE TITLE
Search performance issues

### ISSUE THREAD

**Issue by oker1** [ctdk/goiardi#32]
We're testing goiardi with ~1000 nodes and searches can take 2minutes to complete. I've started with a memory profile build, ran a search, interrupted the process and generated a memory profile of all allocations: https://pdf.yt/d/6HglUhBL9PGPKaOr

It seems like 6G of memory is allocated for a single search with this many nodes.

**Comment by ctdk** [comment]
Aha, I think I see what's going on. For the speed part, one thing that helps immensely is to set GOMAXPROCS to a higher value - this will parallelize searching the indexes, which speeds it up considerably.

The root problem is a little more difficult. The ersatz solr implementation in goiardi is just a little rickety when you stuff that much in. The big change with 0.9.0, actually, was to compress the index data so it wouldn't take up so much space in RAM when it was just sitting there (which does have the unfortunate side effect of making searches a little slower), which is what should be happening, but unfortunately it looks like it's just ballooning up during the searches.

Not all is lost, however. I've been planning for a while to make use of postgres' ltree and/or jsonb capabilities to handle search indexing for bigger cases like this. (From that PDF it looks like you're using postgres with goiardi, so that's good.) I'm in the middle of rewriting the depsolver still, but once I'm done with that I'll move the search stuff up again. For the current index I'll look at reworking it a little to let it free up memory in the middle of searching, while also looking at supporting using postgres' capabilities for searching as well.

Thanks again for putting goiardi through the wringer, by the way. I'm sorry it's been giving you some grief.

**Comment by ctdk** [comment]
Also, to help me duplicate the exact situation, what kind of search are you performing?

**Comment by oker1** [comment]
The search is 'role:role_name' and it matches all nodes.

**Comment by oker1** [comment]
I've been looking at the code, the way I see it is that all documents are stored separately and are scanned one by one for every search. If you try to improve it you would get close to a golang port of Lucene in my opinion. There's already a go Lucene lib, but it does not support some basic features like prefix searches. I think the current implementation could work pretty good for smaller scale, but Solr support would be great for bigger deployments, and it could be identical to the opscode server in functionality.

**Comment by ctdk** [comment]
I think I looked at the same go lucene lib you're talking about when I was first working on getting some kind of search implemented. It had some issues, though, not least of which was that it wouldn't build right on OS X, so I went a different route.

The current implementation works fine on a smaller scale, which is why it's there. I wanted to avoid having to install Solr for a normal use case, and while I had screwed around some with filling in 1000+ fake nodes (and got better results than you, but fauxhai data doesn't exactly reflect real nodes) I hadn't done anything approaching real-world testing with 1000 nodes. Honestly I didn't expect anyone to actually be throwing 1000 nodes at it anytime soon, either.

The reason I brought up the postgres ltree and jsonb stuff was because I had already been thinking about search for larger amounts of data. Real Solr support is certainly an option, but I'd still like to give that a shot first since (in my thinking) Solr is kind of overkill for indexing Chef data. If the postgres thing works then that would be great for larger installations like you were testing, and I could just say that if you have a lot of nodes you should probably use Postgres instead of the in-mem or MySQL backends (which I would say anyway). If not then adding Solr support shouldn't be too hard.

I'm still in the middle of redoing the depsolver, which is something I'd been meaning to do for a while anyway, but I'm already thinking about search and will take a look at that soon. This will be good for the 1.0.0 work anyway, which is getting goiardi up to speed with Chef 12.

**Comment by ctdk** [comment]
This should be addressed with the new postgres search.
